### ISSUE TITLE
Agregar informacion en  handbook 

### ISSUE THREAD

**Issue by Lucasunlp** [Rankmi/handbook#3]
Sobre squash, rebase -i.
Comandos utiles: 
git log --graph
git add . && git commit -m "Algo"
git commit --amend --no-edit

**Comment by fmundaca** [comment]
Lo acabo de agregar https://github.com/Rankmi/handbook/pull/4 @efredz

**Comment by efredz** [comment]
Fixed in [https://github.com/Rankmi/handbook/pull/8](https://github.com/Rankmi/handbook/pull/8)
